### ISSUE TITLE
Explicit versioning and changelog

### ISSUE THREAD

**Issue by Shirikatsu** [clearmatics/asset-token#114]
As a user or developer of the asset token I would like to be able to accurately track the versions and associated features of the project. Now that this is being published with explicit versions on NPM it would be useful to document the changes between each version and identify them in the repository.

**Comment by Andreadinenno** [comment]
I agree. This is done by creating releases right?

**Comment by zoenolan** [comment]
Fixed by https://github.com/clearmatics/asset-token/pull/118
