### ISSUE TITLE
granularity is type uint8, limits values to 255!

### ISSUE THREAD

**Issue by 9areeba** [clearmatics/asset-token#123]
**Is your feature request related to a problem? Please describe.**
The collateral token requires standard denominations depending upon the values of the underlying off chain asset which is likely to be in the thousands/ten of thousands.These standard denominations will be set by using a granularity. Granularity is the smallest amount of tokens that can be sent/ burned. (Eg - if granularity is set to 500 and you want to send 1235 tokens, then it should round up to 1500 tokens.) So using uint8 restricts the max granularity value to 255. 

**Describe the solution you'd like**
Change the granularity type to uint256 to allow higher values of granularity to be set.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by zoenolan** [comment]
Fixed by https://github.com/clearmatics/asset-token/pull/124
