### ISSUE TITLE
What is the real gas consumption?

### ISSUE THREAD

**Issue by eastata** [clearmatics/asset-token#135]
**Describe the bug**
How much is the real gas consumption?
the `gas: 1500000` not enough

**To Reproduce**
Deploy contract to new network with:
`truffle.js`:
```js
var Web3 = require("web3");
var PrivateKeyProvider = require("truffle-privatekey-provider");
var privateKey = "?????";

module.exports = {
  networks: {
    apw4: {
      provider: new PrivateKeyProvider(privateKey, "http://localhost:8545"),
      gas: 1500000,
      gasPrice: 211398613,
      network_id: '*',
   }
  },
  solc: {
    optimizer: {
      enabled: true,
      runs: 200
    },
    version: "0.5.3+commit.10d17f24"
  }
};
```
`oz create`:
```
? Pick a contract to instantiate AssetToken
? Pick a network apw4
? One or more linked dependencies are not yet deployed on dev-444889.
Do you want to deploy them now? Yes
✖ Deploying openzeppelin-eth dependency to network dev-444889
Failed deployment of dependency openzeppelin-eth with error: The contract code couldn't be stored, please check your gas limit.
```

**Additional context**
If no other docs, can we get tx from an existing network where contract was successfully deployed and check `gas used`? Is it will the same for any networks?

**Comment by eastata** [comment]
Truffle default is `6721975`

**Comment by Andreadinenno** [comment]
We deployed to SystemX MVP using `zos` that uses `truffle` under the hood. If you deploy with `truffle migrate`, by adding to the network the config `skipDryRun : false` (which probably is the default), it will tell you an approximation of the gas consumption.
