### ISSUE TITLE
Code coverage generation is broken

### ISSUE THREAD

**Issue by shapeshed** [clearmatics/asset-token#138]
**Describe the bug**
Running code coverage reports is broken.

**To Reproduce**
1. run `yarn coverage`
2. See that the code coverage generation fails

**Expected behavior**
It should generate a code coverage report

**Additional context**
Once fixed the continuous integration task should be updated to submit code coverage reports to codecov.

**Comment by zoenolan** [comment]
Duplicate of https://github.com/clearmatics/asset-token/issues/93
