### ISSUE TITLE
Tighter type for `status` argument in `AssetToken.sol`

### ISSUE THREAD

**Issue by AntoineRondelet** [clearmatics/asset-token#157]
From what I can see, the `status` argument https://github.com/clearmatics/asset-token/blob/develop/contracts/AssetToken.sol#L66 is of type int. Is that strictly necessary?

Seems like:
1. It does not need to be signed
2. It can fit in a `uint8`

Let me know if I missed something :)

**Comment by Andreadinenno** [comment]
Thanks for the catch Antoine! 
It's been fixed in https://github.com/clearmatics/asset-token/pull/158
