### ISSUE TITLE
Defund entire balance

### ISSUE THREAD

**Issue by sc-117** [clearmatics/asset-token#37]
Asset-token.sol, line 53,  function defund(uint256 value) 
if (balanceOf(msg.sender) < value) revert();

"<" implies the msg.sender cannot defund its full balance.

**Comment by zoenolan** [comment]
I think the code is correct as is.

for example with the balance as 50 and the value as 50
if (50 < 50) revert();
The revert would not be triggered, which is the behaviour we want
