### ISSUE TITLE
Add ERC20 compatible Transfer Events

### ISSUE THREAD

**Issue by GoldenDave** [clearmatics/asset-token#78]
Just wanted to check with you that you understand that by emitting ERC223 events rather than ERC20 events your token transfers are less likely to ever be handled by etherscan.

Of the 14 or so ERC223 contracts in the wild, only about four of them use the ERC223 version of the Transfer event. Calling it with Empty still emits the same event.

If your token is for use inside a closed system that is not a  problem. If it is being used generally, ERC20 event compatibility is avisable.

**Comment by zoenolan** [comment]
Our current use case is with a closed system but you do raise a good point. Our reasons for open sourcing the code was so others can reuse what we have done.

I've edited the issue title to make the work required clear

**Comment by zoenolan** [comment]
Since we have #87 that covers a superset of this issue, closing this one
