### ISSUE TITLE
Why not reuse an existing contract library?

### ISSUE THREAD

**Issue by magooster** [clearmatics/asset-token#80]
Why does the asset token contract not reuse an existing contract library - such as OpenZeppelin. Your asset token contract could then just implement the additionally functionality that supports the use-case.

**Comment by zoenolan** [comment]
We had created the initial version before we were aware of OpenZeppelin. If we were starting today, I'm sure we would just go with a contract library.

**Comment by zoenolan** [comment]
Just to update this. open Zeppelin have said [they will not be supporting ERC223 ](https://github.com/OpenZeppelin/openzeppelin-solidity/issues/512) anytime soon

**Comment by zoenolan** [comment]
[Switching over to Open Zeppelin's SafeMath](https://github.com/clearmatics/asset-token/pull/85)

**Comment by zoenolan** [comment]
[Switch to the Open Zeppelin version of the ERC20 interface](https://github.com/clearmatics/asset-token/pull/86)

**Comment by zoenolan** [comment]
Now [Upgradable](https://github.com/clearmatics/asset-token/pull/92)

**Comment by zoenolan** [comment]
We have switched over to OpenZeppelin. so I'm going to close this for now. We may make use of more of OpenZeppelin or another library depending on [which token standards we end up supporting](https://github.com/clearmatics/asset-token/issues/88)
