### ISSUE TITLE
Add transfer endpoints Tests

### ISSUE THREAD

**Issue by zoenolan** [clearmatics/asset-token#9]
Three variants: 
* function transfer(address to, uint value) public returns (bool ok);
* function transfer(address to, uint value, bytes data) public returns (bool ok);
* function transfer(address to, uint value, bytes data, string custom_fallback) public returns (bool ok);

**Comment by zoenolan** [comment]
This should be done after #2

**Comment by zoenolan** [comment]
Checking the coverage output. Any paths not covered by existing tests should have tests created to exercise them.

**Comment by aneequesafdar** [comment]
For each of the above three functions we need to cover the following cases:
- Transfer from `EOA ==> EOA`
- Transfer from `EOA ==> Contract`
- Transfer from `Contract ==> EOA`
- Transfer from `Contract ==> Contract`

Mock contracts will need to be created to test for this.

For the transfers involving contracts we need to check for `tokenFallback()`, `customFallback()` and in the case of ERC20 the reciving contract handling  transferring events. Thus there will be 2 test cases each.
