### ISSUE TITLE
Solidity-coverage missing dependencies with web3 1.0.0-beta.51

### ISSUE THREAD

**Issue by Andreadinenno** [clearmatics/asset-token#93]
This issue is a remainder to check updates of [solidity-coverage](https://github.com/sc-forks/solidity-coverage), since in its last implementation it is using web3 beta.50. 

This is needed because of an [issue](https://github.com/ethereum/web3.js/issues/2542) of web3, that causes roughly half of our test to fail when run under the solidity-coverage environment, while passing using the latest Truffle/Ganache.

**Comment by zoenolan** [comment]
This is currently blocking #97

**Comment by zoenolan** [comment]
A [beta version](https://github.com/sc-forks/solidity-coverage/pull/318) of solidity-coverage with support for Solidity 0.5.x but is currently untested

**Comment by zoenolan** [comment]
and after testing the [latest beta version](https://www.npmjs.com/package/solidity-coverage/v/0.6.0-beta.5) that is still producing the error.

**Comment by zoenolan** [comment]
[New release of sol-coverage](https://github.com/sc-forks/solidity-coverage/releases/tag/v0.6.0), not a simple drop in upgrade

**Comment by zoenolan** [comment]
[v0.6.4](https://github.com/sc-forks/solidity-coverage/releases/tag/v0.6.4) released a while back

**Comment by Andreadinenno** [comment]
Updated to the latest version of solidity-coverage yet same errors when running the coverage.
Steps to reproduce:
- remove node modules with `rm -rf node_modules`
- update `solidity-coverage` in `package.json` to version `0.6.4`
- fresh install dependencies `npm install`
- run test coverage tool `npm run coverage`

Error encountered: 
`TypeError: Overriding function changes state mutability from "view" to "nonpayable"` for a bunch of function implementing the `IERC777`

**Comment by Andreadinenno** [comment]
Fixed in https://github.com/clearmatics/asset-token/pull/143
