### ISSUE TITLE
Funding and emergency stop delegates should not be able to transact using the token

### ISSUE THREAD

**Issue by zoenolan** [clearmatics/asset-token#96]
### Prerequisites

* [x] Are you running the latest version?
* [x] Are you reporting to the correct repository?
* [x] Did you perform a cursory search?

### Description

Previously the owner of the contract was not allowed to perform payment operations. with the change to delegating control of fund and emergency stop operations. Those  delegated accounts are not stopped from performing payment operations 

### Steps to Reproduce

1. Delegate funding to an account
2. Try to make a payment as that account

**Expected behavior:** [What you expected to happen]
Payment refused

**Actual behavior:** [What actually happened]
Payment is successful

**Comment by Andreadinenno** [comment]
shall the owner be able to make payments once has delegated?

**Comment by zoenolan** [comment]
I think generally our philosophy is to keep the two roles separate.  An address can either manage the operation of the network or be able to do transactions. So the owner should not be able to make payments once delegated
